In [77]:
# import zipfile
# with zipfile.ZipFile("output6.zip") as zip_ref:
#     zip_ref.extractall()

In [78]:
import pandas as pd

# Read the CSV files
df1 = pd.read_csv('output5.csv')
df2 = pd.read_csv('output6.csv')
df3 = pd.read_csv('output7.csv')
df4 = pd.read_csv('output8.csv')

# Get the column names for each DataFrame
columns_df1 = list(df1.columns)
columns_df2 = list(df2.columns)
columns_df3 = list(df3.columns)
columns_df4 = list(df4.columns)

# Function to compare columns index by index
def compare_columns(columns1, columns2):
    differences = []
    for i, (col1, col2) in enumerate(zip(columns1, columns2)):
        if col1 != col2:
            differences.append((i, col1, col2))
    return differences

# Check for differences
differences_df1_df2 = compare_columns(columns_df1, columns_df2)
differences_df1_df3 = compare_columns(columns_df1, columns_df3)
differences_df1_df4 = compare_columns(columns_df1, columns_df4)
differences_df2_df3 = compare_columns(columns_df2, columns_df3)
differences_df2_df4 = compare_columns(columns_df2, columns_df4)
differences_df3_df4 = compare_columns(columns_df3, columns_df4)

# Print the differences
def print_differences(differences, name1, name2):
    if differences:
        print(f"Differences between {name1} and {name2}:")
        for diff in differences:
            print(f"Index {diff[0]}: {diff[1]} != {diff[2]}")
    else:
        print(f"No differences between {name1} and {name2}")

print_differences(differences_df1_df2, 'df1', 'df2')
print_differences(differences_df1_df3, 'df1', 'df3')
print_differences(differences_df1_df4, 'df1', 'df4')
print_differences(differences_df2_df3, 'df2', 'df3')
print_differences(differences_df2_df4, 'df2', 'df4')
print_differences(differences_df3_df4, 'df3', 'df4')

No differences between df1 and df2
Differences between df1 and df3:
Index 19: maximum area this plant require(inches) != Maximum area this plant require (inches)
Index 20: soil depth for sowing(inches) != Soil depth for sowing (inches)
Differences between df1 and df4:
Index 13: Heat Wave Maximum Temprature (°C) != Heat Wave Maximum Temperature (°C)
Differences between df2 and df3:
Index 19: maximum area this plant require(inches) != Maximum area this plant require (inches)
Index 20: soil depth for sowing(inches) != Soil depth for sowing (inches)
Differences between df2 and df4:
Index 13: Heat Wave Maximum Temprature (°C) != Heat Wave Maximum Temperature (°C)
Differences between df3 and df4:
Index 13: Heat Wave Maximum Temprature (°C) != Heat Wave Maximum Temperature (°C)
Index 19: Maximum area this plant require (inches) != maximum area this plant require(inches)
Index 20: Soil depth for sowing (inches) != soil depth for sowing(inches)

In [79]:
rename_dict1 = {
    "maximum area this plant require(inches)" : "Maximum area this plant require (inches)",
    "soil depth for sowing(inches)" : "Soil depth for sowing (inches)"
}
df1.rename(columns=rename_dict1,inplace=True)

In [80]:
import pandas as pd


# Get the column names for each DataFrame
columns_df1 = list(df1.columns)
columns_df2 = list(df2.columns)
columns_df3 = list(df3.columns)
columns_df4 = list(df4.columns)

# Function to compare columns index by index
def compare_columns(columns1, columns2):
    differences = []
    for i, (col1, col2) in enumerate(zip(columns1, columns2)):
        if col1 != col2:
            differences.append((i, col1, col2))
    return differences

# Check for differences
# differences_df1_df2 = compare_columns(columns_df1, columns_df2)
# differences_df1_df3 = compare_columns(columns_df1, columns_df3)
differences_df1_df4 = compare_columns(columns_df1, columns_df4)
differences_df2_df3 = compare_columns(columns_df2, columns_df3)
differences_df2_df4 = compare_columns(columns_df2, columns_df4)
differences_df3_df4 = compare_columns(columns_df3, columns_df4)

# Print the differences
def print_differences(differences, name1, name2):
    if differences:
        print(f"Differences between {name1} and {name2}:")
        for diff in differences:
            print(f"Index {diff[0]}: {diff[1]} != {diff[2]}")
    else:
        print(f"No differences between {name1} and {name2}")

# print_differences(differences_df1_df2, 'df1', 'df2')
# print_differences(differences_df1_df3, 'df1', 'df3')
print_differences(differences_df1_df4, 'df1', 'df4')
print_differences(differences_df2_df3, 'df2', 'df3')
print_differences(differences_df2_df4, 'df2', 'df4')
print_differences(differences_df3_df4, 'df3', 'df4')

Differences between df1 and df4:
Index 13: Heat Wave Maximum Temprature (°C) != Heat Wave Maximum Temperature (°C)
Index 19: Maximum area this plant require (inches) != maximum area this plant require(inches)
Index 20: Soil depth for sowing (inches) != soil depth for sowing(inches)
Differences between df2 and df3:
Index 19: maximum area this plant require(inches) != Maximum area this plant require (inches)
Index 20: soil depth for sowing(inches) != Soil depth for sowing (inches)
Differences between df2 and df4:
Index 13: Heat Wave Maximum Temprature (°C) != Heat Wave Maximum Temperature (°C)
Differences between df3 and df4:
Index 13: Heat Wave Maximum Temprature (°C) != Heat Wave Maximum Temperature (°C)
Index 19: Maximum area this plant require (inches) != maximum area this plant require(inches)
Index 20: Soil depth for sowing (inches) != soil depth for sowing(inches)

In [81]:
df4.columns

Index(['Plant Category', 'Seed Name', 'Average Temperature (2 m)',
       'Average Precipitation per day', 'Average Soil Temperature (0 to 6 cm)',
       'Average Soil Moisture (0-3 cm)', 'Average Evapotranspiration',
       'Average Sunshine Duration', 'Humidity(%)', 'Soil Type',
       'Best Growing Areas', 'Season', 'Wind Threshold(km/h)',
       'Heat Wave Maximum Temperature (°C)',
       'Rainfall Alert Maximum Rain (mm)', 'Watering (hours interval)',
       'List of Fertilization',
       'Time Period for Fertilization (weeks interval)',
       'Maximum Height of Plant (inches)',
       'maximum area this plant require(inches)',
       'soil depth for sowing(inches)', 'Plant name'],
      dtype='object')

In [82]:
dict4={"Heat Wave Maximum Temperature (°C)":"Heat Wave Maximum Temprature (°C)",
         "maximum area this plant require(inches)":"Maximum area this plant require (inches)",
         "soil depth for sowing(inches)":"Soil depth for sowing (inches)"}
df4.rename(columns=dict4,inplace=True)

In [83]:
import pandas as pd


# Get the column names for each DataFrame
columns_df1 = list(df1.columns)
columns_df2 = list(df2.columns)
columns_df3 = list(df3.columns)
columns_df4 = list(df4.columns)

# Function to compare columns index by index
def compare_columns(columns1, columns2):
    differences = []
    for i, (col1, col2) in enumerate(zip(columns1, columns2)):
        if col1 != col2:
            differences.append((i, col1, col2))
    return differences

# Check for differences
# differences_df1_df2 = compare_columns(columns_df1, columns_df2)
# differences_df1_df3 = compare_columns(columns_df1, columns_df3)
differences_df1_df4 = compare_columns(columns_df1, columns_df4)
differences_df2_df3 = compare_columns(columns_df2, columns_df3)
differences_df2_df4 = compare_columns(columns_df2, columns_df4)
differences_df3_df4 = compare_columns(columns_df3, columns_df4)

# Print the differences
def print_differences(differences, name1, name2):
    if differences:
        print(f"Differences between {name1} and {name2}:")
        for diff in differences:
            print(f"Index {diff[0]}: {diff[1]} != {diff[2]}")
    else:
        print(f"No differences between {name1} and {name2}")

# print_differences(differences_df1_df2, 'df1', 'df2')
# print_differences(differences_df1_df3, 'df1', 'df3')
print_differences(differences_df1_df4, 'df1', 'df4')
# print_differences(differences_df2_df3, 'df2', 'df3')
# print_differences(differences_df2_df4, 'df2', 'df4')
# print_differences(differences_df3_df4, 'df3', 'df4')

No differences between df1 and df4

In [84]:
import pandas as pd


# Get the column names for each DataFrame
columns_df1 = list(df1.columns)
columns_df2 = list(df2.columns)
columns_df3 = list(df3.columns)
columns_df4 = list(df4.columns)

# Function to compare columns index by index
def compare_columns(columns1, columns2):
    differences = []
    for i, (col1, col2) in enumerate(zip(columns1, columns2)):
        if col1 != col2:
            differences.append((i, col1, col2))
    return differences

# Check for differences
# differences_df1_df2 = compare_columns(columns_df1, columns_df2)
differences_df1_df3 = compare_columns(columns_df1, columns_df3)
differences_df1_df4 = compare_columns(columns_df1, columns_df4)
differences_df2_df3 = compare_columns(columns_df2, columns_df3)
differences_df2_df4 = compare_columns(columns_df2, columns_df4)
differences_df3_df4 = compare_columns(columns_df3, columns_df4)

# Print the differences
def print_differences(differences, name1, name2):
    if differences:
        print(f"Differences between {name1} and {name2}:")
        for diff in differences:
            print(f"Index {diff[0]}: {diff[1]} != {diff[2]}")
    else:
        print(f"No differences between {name1} and {name2}")

# print_differences(differences_df1_df2, 'df1', 'df2')
print_differences(differences_df1_df3, 'df1', 'df3')
# print_differences(differences_df1_df4, 'df1', 'df4')
print_differences(differences_df2_df3, 'df2', 'df3')
print_differences(differences_df2_df4, 'df2', 'df4')
print_differences(differences_df3_df4, 'df3', 'df4')

No differences between df1 and df3
Differences between df2 and df3:
Index 19: maximum area this plant require(inches) != Maximum area this plant require (inches)
Index 20: soil depth for sowing(inches) != Soil depth for sowing (inches)
Differences between df2 and df4:
Index 19: maximum area this plant require(inches) != Maximum area this plant require (inches)
Index 20: soil depth for sowing(inches) != Soil depth for sowing (inches)
No differences between df3 and df4

In [85]:
dict2={"maximum area this plant require(inches)":"Maximum area this plant require (inches)",
"soil depth for sowing(inches)":"Soil depth for sowing (inches)"}
df2.rename(columns=dict2,inplace=True)

In [86]:
import pandas as pd


# Get the column names for each DataFrame
columns_df1 = list(df1.columns)
columns_df2 = list(df2.columns)
columns_df3 = list(df3.columns)
columns_df4 = list(df4.columns)

# Function to compare columns index by index
def compare_columns(columns1, columns2):
    differences = []
    for i, (col1, col2) in enumerate(zip(columns1, columns2)):
        if col1 != col2:
            differences.append((i, col1, col2))
    return differences

# Check for differences
differences_df1_df2 = compare_columns(columns_df1, columns_df2)
differences_df1_df3 = compare_columns(columns_df1, columns_df3)
differences_df1_df4 = compare_columns(columns_df1, columns_df4)
differences_df2_df3 = compare_columns(columns_df2, columns_df3)
differences_df2_df4 = compare_columns(columns_df2, columns_df4)
differences_df3_df4 = compare_columns(columns_df3, columns_df4)

# Print the differences
def print_differences(differences, name1, name2):
    if differences:
        print(f"Differences between {name1} and {name2}:")
        for diff in differences:
            print(f"Index {diff[0]}: {diff[1]} != {diff[2]}")
    else:
        print(f"No differences between {name1} and {name2}")

print_differences(differences_df1_df2, 'df1', 'df2')
print_differences(differences_df1_df3, 'df1', 'df3')
print_differences(differences_df1_df4, 'df1', 'df4')
print_differences(differences_df2_df3, 'df2', 'df3')
print_differences(differences_df2_df4, 'df2', 'df4')
print_differences(differences_df3_df4, 'df3', 'df4')

No differences between df1 and df2
No differences between df1 and df3
No differences between df1 and df4
No differences between df2 and df3
No differences between df2 and df4
No differences between df3 and df4

In [87]:
merged = pd.concat([df1,df2,df3,df4],ignore_index=True)

In [88]:
merged.to_csv('merged.csv', index=False)

In [1]:
import pandas as pd
merged_df =pd.read_csv("merged.csv")
merged_df

In [ ]:
merged_df_copy=merged_df
merged_df_copy

,Plant Category,Seed Name,Average Temperature (2 m),Average Precipitation per day,Average Soil Temperature (0 to 6 cm),Average Soil Moisture (0-3 cm),Average Evapotranspiration,Average Sunshine Duration,Humidity(%),Soil Type,...,Wind Threshold(km/h),Heat Wave Maximum Temprature (°C),Rainfall Alert Maximum Rain (mm),Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Maximum Height of Plant (inches),Maximum area this plant require (inches),Soil depth for sowing (inches),Plant name
0,Herbaceous perennial,Monarde citron,22.5,3.5,18,0.25,3,30000,70,"[""Loam"",""Sandy loam"",""Clay loam""]",...,40,35,25,48,"[""Organic compost"",""Liquid seaweed fertilizer""]",4,36,12,1,monarde citron
1,Flowering Plant,Montana Jack,18°C,10 mm,15°C,0.3 m³/m³,5 mm/day,8 hours,60%,"[""Loam"",""Sandy Loam"",""Clay Loam""]",...,50 km/h,35°C,50 mm,48 hours,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8 weeks,24 inches,12 inches,1 inch,montana jack
2,Flower,Moravsky Div,22,5,18,0.3,4,18000,60,"[""Loam"",""Sandy Loam""]",...,40,35,20,24,"[""NPK 10-10-10"",""Compost""]",4,24,12,0.5,moravsky div
3,Flowering Plant,Morden Early,22,5,18,0.3,3,300,60,"[""Loam"",""Clay"",""Sandy""]",...,40,35,20,24,"[""Organic compost"",""Slow-release granular fert...",4,24,12,0.5,morden early
4,Tomato,Mortgage Lifter,18,5,22,0.3,3,3000,70,"[""Loam"",""Sandy Loam"",""Clay Loam""]",...,40,35,50,24,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2,72,36,1,mortgage lifter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,20-25,5-10,15-20,0.2-0.3,3-5,6-8,40-60,"[""Sandy loam"",""Loamy sand"",""Clay loam""]",...,40-60,30-35,20-30,24-48,"[""Organic compost"",""Slow-release granular fert...",4-6,12-18,12-18,0.25-0.5,ursinia anthemoides
4090,Herb,Valeriana Locusta,16,5,18,0.3,3,6000,60,"[""Loam"",""Sandy loam""]",...,40,35,40,72,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,24,12,0.5,valeriana locusta
4091,Herb,Valerianella Dentata,18,5,15,0.4,3,300,60,"[""Loamy"",""Sandy""]",...,40,30,10,48,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,12,6,0.5,valerianella dentata
4092,Flowering Perennial,Verbascum roripifolium,18,5,15,0.3,3,24000,60,"[""Loam"",""Sandy Loam"",""Clay""]",...,40,35,50,48,"[""Organic compost"",""All-purpose slow-release f...",6,36,144,0.25,verbascum roripifolium
4093,Flowering Plant,Zinnia Violacea,25,5,20,0.3,3,6000,50,"[""Loam"",""Sandy Loam"",""Clay""]",...,40,35,20,24,"[""NPK 10-10-10"",""Organic compost""]",4,36,12,0.5,zinnia violacea

In [ ]:
merged_df.columns

Index(['Plant Category', 'Seed Name', 'Average Temperature (2 m)',
       'Average Precipitation per day', 'Average Soil Temperature (0 to 6 cm)',
       'Average Soil Moisture (0-3 cm)', 'Average Evapotranspiration',
       'Average Sunshine Duration', 'Humidity(%)', 'Soil Type',
       'Best Growing Areas', 'Season', 'Wind Threshold(km/h)',
       'Heat Wave Maximum Temprature (°C)', 'Rainfall Alert Maximum Rain (mm)',
       'Watering (hours interval)', 'List of Fertilization',
       'Time Period for Fertilization (weeks interval)',
       'Maximum Height of Plant (inches)',
       'Maximum area this plant require (inches)',
       'Soil depth for sowing (inches)', 'Plant name'],
      dtype='object')

In [4]:
seedData=merged_df_copy[["Plant Category","Seed Name","Average Precipitation per day","Average Temperature (2 m)","Average Soil Temperature (0 to 6 cm)","Average Sunshine Duration","Humidity(%)","Rainfall Alert Maximum Rain (mm)","Average Soil Moisture (0-3 cm)"]]
seedData

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18,30000,70,25,0.25
1,Flowering Plant,Montana Jack,10 mm,18°C,15°C,8 hours,60%,50 mm,0.3 m³/m³
2,Flower,Moravsky Div,5,22,18,18000,60,20,0.3
3,Flowering Plant,Morden Early,5,22,18,300,60,20,0.3
4,Tomato,Mortgage Lifter,5,18,22,3000,70,50,0.3
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,5-10,20-25,15-20,6-8,40-60,20-30,0.2-0.3
4090,Herb,Valeriana Locusta,5,16,18,6000,60,40,0.3
4091,Herb,Valerianella Dentata,5,18,15,300,60,10,0.4
4092,Flowering Perennial,Verbascum roripifolium,5,18,15,24000,60,50,0.3
4093,Flowering Plant,Zinnia Violacea,5,25,20,6000,50,20,0.3

In [5]:
import numpy as np
seedData["Seed Name"]=seedData["Seed Name"].replace(" ",np.nan)

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1803902015.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Seed Name"]=seedData["Seed Name"].replace(" ",np.nan)

In [6]:
seedData["Seed Name"].isna().sum()

12

In [7]:
seedData.dropna(subset=["Seed Name"],inplace=True)
for i in seedData.index:
    if seedData.loc[i,"Seed Name"]=="Unknown":
        seedData.drop(i,inplace=True)
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3422348969.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData.dropna(subset=["Seed Name"],inplace=True)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3422348969.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData.drop(i,inplace=True)

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18,30000,70,25,0.25
1,Flowering Plant,Montana Jack,10 mm,18°C,15°C,8 hours,60%,50 mm,0.3 m³/m³
2,Flower,Moravsky Div,5,22,18,18000,60,20,0.3
3,Flowering Plant,Morden Early,5,22,18,300,60,20,0.3
4,Tomato,Mortgage Lifter,5,18,22,3000,70,50,0.3
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,5-10,20-25,15-20,6-8,40-60,20-30,0.2-0.3
4090,Herb,Valeriana Locusta,5,16,18,6000,60,40,0.3
4091,Herb,Valerianella Dentata,5,18,15,300,60,10,0.4
4092,Flowering Perennial,Verbascum roripifolium,5,18,15,24000,60,50,0.3
4093,Flowering Plant,Zinnia Violacea,5,25,20,6000,50,20,0.3

In [8]:
seedData["Seed Name"].isna().sum()

0

In [9]:
seedData.head()

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18,30000,70,25,0.25
1,Flowering Plant,Montana Jack,10 mm,18°C,15°C,8 hours,60%,50 mm,0.3 m³/m³
2,Flower,Moravsky Div,5,22,18,18000,60,20,0.3
3,Flowering Plant,Morden Early,5,22,18,300,60,20,0.3
4,Tomato,Mortgage Lifter,5,18,22,3000,70,50,0.3

In [10]:
seedData["Average Precipitation per day"].unique()

array(['3.5', '10 mm', '5', '10', '6.2', '4', '5 mm', '2-4', '2.3', '8.7',
       '3', '5-10', '8.2', '2-5', '10-15', '4.9', '5.6', '2', '5 - 10',
       '5mm', '12.3', '1-5', '5.2', '2.5', ' ', '0', '3-6', '5.7',
       '5 to 10', '1-2', '5-15', '10.2', '3.2', '5.4', '3-5', '3.8',
       '4 mm', '5.3', '5.8', '3 mm', '10-20', '3.4', '5.7 mm', '3.2 mm',
       '5-20', '1-3', '4.7', '10 - 20', '10mm', '2-3', '4.5', '2-3 mm',
       '2 - 4', '6.7', 'Varies depending on the region', '4.2', '3 - 5',
       '5.2 mm', nan, '10.2 mm', '7.8', '4.3', '0-5', '2-7', '2.8',
       '2-5 mm', '5-10 mm', '8', '2.5mm', '6.3', '2 mm', '2 - 5',
       '2-4 mm', '6', '1-3 mm', '4-8', '4.6', '1.5', '0.5-1.0', '2.5 mm',
       '1 - 5', '2 - 5 mm', '3.1', '5-30', '8.9', '2 to 5', '5 - 20',
       '4.8'], dtype=object)

In [11]:
seedData["Average Precipitation per day"] = seedData["Average Precipitation per day"].str.strip(" m")
seedData["Average Precipitation per day"].isna().sum()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1655727316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Precipitation per day"] = seedData["Average Precipitation per day"].str.strip(" m")

1

In [12]:
seedData["Average Precipitation per day"]=seedData["Average Precipitation per day"].str.replace("to","-")
seedData["Average Precipitation per day"]=seedData["Average Precipitation per day"].str.replace(" ","")
seedData["Average Precipitation per day"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3870573734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Precipitation per day"]=seedData["Average Precipitation per day"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3870573734.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Precipitation per day"]=seedData["Average Precipitation per day"].str.replace(" ","")

array(['3.5', '10', '5', '6.2', '4', '2-4', '2.3', '8.7', '3', '5-10',
       '8.2', '2-5', '10-15', '4.9', '5.6', '2', '12.3', '1-5', '5.2',
       '2.5', '', '0', '3-6', '5.7', '1-2', '5-15', '10.2', '3.2', '5.4',
       '3-5', '3.8', '5.3', '5.8', '10-20', '3.4', '5-20', '1-3', '4.7',
       '2-3', '4.5', '6.7', 'Variesdependingontheregion', '4.2', nan,
       '7.8', '4.3', '0-5', '2-7', '2.8', '8', '6.3', '6', '4-8', '4.6',
       '1.5', '0.5-1.0', '3.1', '5-30', '8.9', '4.8'], dtype=object)

In [13]:
def replace_str_nan(value):
    if value == "":
        return np.nan
    else:
        return value

In [14]:
# seedData["Average Precipitation per day"] = seedData["Average Precipitation per day"].replace(r"[a-zA-Z]",np.nan)
seedData.loc[seedData["Average Precipitation per day"].str.contains(r"[a-zA-Z]", na=False), "Average Precipitation per day"] = np.nan
# seedData["Average Precipitation per day"].unique()
seedData["Average Precipitation per day"] = seedData["Average Precipitation per day"].apply(replace_str_nan)
seedData["Average Precipitation per day"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\610636096.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Precipitation per day"] = seedData["Average Precipitation per day"].apply(replace_str_nan)

array(['3.5', '10', '5', '6.2', '4', '2-4', '2.3', '8.7', '3', '5-10',
       '8.2', '2-5', '10-15', '4.9', '5.6', '2', '12.3', '1-5', '5.2',
       '2.5', nan, '0', '3-6', '5.7', '1-2', '5-15', '10.2', '3.2', '5.4',
       '3-5', '3.8', '5.3', '5.8', '10-20', '3.4', '5-20', '1-3', '4.7',
       '2-3', '4.5', '6.7', '4.2', '7.8', '4.3', '0-5', '2-7', '2.8', '8',
       '6.3', '6', '4-8', '4.6', '1.5', '0.5-1.0', '3.1', '5-30', '8.9',
       '4.8'], dtype=object)

In [15]:
def calculate_mean_value(value):
    if "-" in value:
        parts=value.split("-")
        if len(parts) ==2 and parts[0] != "":
        
            # min_val,max_val = map(float,value.split("-"))
            min_val,max_val = [float(i) for i in parts]
            # In Python, float is a built-in function that converts a string or a number to a floating-point number. It is used in the map function without parentheses because float is being passed as an argument to map, not being called directly.
            return (min_val+max_val)/2
        else:
            return float(value)
        
    else:
        return float(value)

In [16]:
# seedData[["Average Precipitation per day(min)","Average Precipitation per day(max)"]] = seedData["Average Precipitation per day"].astype(str).str.split("-",n=1,expand=True)
seedData["Average Precipitation per day"]=seedData["Average Precipitation per day"].astype(str).apply(calculate_mean_value)
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\147735037.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Precipitation per day"]=seedData["Average Precipitation per day"].astype(str).apply(calculate_mean_value)

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18,30000,70,25,0.25
1,Flowering Plant,Montana Jack,10.0,18°C,15°C,8 hours,60%,50 mm,0.3 m³/m³
2,Flower,Moravsky Div,5.0,22,18,18000,60,20,0.3
3,Flowering Plant,Morden Early,5.0,22,18,300,60,20,0.3
4,Tomato,Mortgage Lifter,5.0,18,22,3000,70,50,0.3
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,20-25,15-20,6-8,40-60,20-30,0.2-0.3
4090,Herb,Valeriana Locusta,5.0,16,18,6000,60,40,0.3
4091,Herb,Valerianella Dentata,5.0,18,15,300,60,10,0.4
4092,Flowering Perennial,Verbascum roripifolium,5.0,18,15,24000,60,50,0.3
4093,Flowering Plant,Zinnia Violacea,5.0,25,20,6000,50,20,0.3

In [17]:
seedData["Average Precipitation per day"].fillna(seedData["Average Precipitation per day"].mean(),inplace=True)
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\2020743655.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  seedData["Average Precipitation per day"].fillna(seedData["Average Precipitation per day"].mean(),inplace=True)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\2020743655.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Precipitation per day"].fillna(seedData["Average Precipitation per day"].mean(),inplace=True)

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18,30000,70,25,0.25
1,Flowering Plant,Montana Jack,10.0,18°C,15°C,8 hours,60%,50 mm,0.3 m³/m³
2,Flower,Moravsky Div,5.0,22,18,18000,60,20,0.3
3,Flowering Plant,Morden Early,5.0,22,18,300,60,20,0.3
4,Tomato,Mortgage Lifter,5.0,18,22,3000,70,50,0.3
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,20-25,15-20,6-8,40-60,20-30,0.2-0.3
4090,Herb,Valeriana Locusta,5.0,16,18,6000,60,40,0.3
4091,Herb,Valerianella Dentata,5.0,18,15,300,60,10,0.4
4092,Flowering Perennial,Verbascum roripifolium,5.0,18,15,24000,60,50,0.3
4093,Flowering Plant,Zinnia Violacea,5.0,25,20,6000,50,20,0.3

In [18]:
seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].str.replace("to","-")
seedData["Average Temperature (2 m)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\948572455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].str.replace("to","-")

array(['22.5', '18°C', '22', '18', '20', '25', '25.6', '21', '20 °C',
       '18-25', '24.5', '28.5', '15', '24', '26', '15-25', '20-25',
       '27.5', '25 °C', '23', '18 - 25', '18-27', '-5', '10-24', '25.5',
       '28', ' ', '30', '20°C', '16', '14.5', '10-20', '19', '10-25',
       '16.5', '20.5', '8-15', '10', '15 - 25', '12.5', '12', '18.5',
       '15-30', '15-20', '15 °C', '10°C', '10-15', '12 °C', '10.5',
       '25°C', '21.5', '17', '7', '12.5 °C', '18-24', '14', '15.5',
       '18.5°C', '5-20', '15.6', '17.5', '10-15°C', '10 - 20', '22 °C',
       '18 °C', '15.3', '19.7', '15 - 20', '-5.8', '10-30 °C', '10 °C',
       '20 - 30', '20-30', '25-35', '10.5°C', '20-24', '23.5', '20 - 25',
       '25.5 °C', '10-18 °C', '20-25°C', '8-20', '15°C', '12.5°C',
       '10 - 25', '22°C', '10-18', '8 - 20', '10-20°C', '18-30', '8-20°C',
       '18.6', '10-30', '15-20 °C', '21 °C', '8-25', '5-25', '20.3',
       '4.5', '10.5 °C', '18-22', '25-30', '10-35', '27', '8 - 24',
       '15 - 27 °C', '12-16', '16 °C', '7.5 °C', '10-21°C', '-10', '25.3',
       '5 - 15', '30.5', '10.6', '5 - 20', '19.5', '18-26', '7.5'],
      dtype=object)

In [19]:
seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].str.replace(" ","")
seedData["Average Temperature (2 m)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1241840954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].str.replace(" ","")

array(['22.5', '18°C', '22', '18', '20', '25', '25.6', '21', '20°C',
       '18-25', '24.5', '28.5', '15', '24', '26', '15-25', '20-25',
       '27.5', '25°C', '23', '18-27', '-5', '10-24', '25.5', '28', '',
       '30', '16', '14.5', '10-20', '19', '10-25', '16.5', '20.5', '8-15',
       '10', '12.5', '12', '18.5', '15-30', '15-20', '15°C', '10°C',
       '10-15', '12°C', '10.5', '21.5', '17', '7', '12.5°C', '18-24',
       '14', '15.5', '18.5°C', '5-20', '15.6', '17.5', '10-15°C', '22°C',
       '15.3', '19.7', '-5.8', '10-30°C', '20-30', '25-35', '10.5°C',
       '20-24', '23.5', '25.5°C', '10-18°C', '20-25°C', '8-20', '10-18',
       '10-20°C', '18-30', '8-20°C', '18.6', '10-30', '15-20°C', '21°C',
       '8-25', '5-25', '20.3', '4.5', '18-22', '25-30', '10-35', '27',
       '8-24', '15-27°C', '12-16', '16°C', '7.5°C', '10-21°C', '-10',
       '25.3', '5-15', '30.5', '10.6', '19.5', '18-26', '7.5'],
      dtype=object)

In [20]:
seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].str.strip(" °C")
seedData["Average Temperature (2 m)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1497665124.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].str.strip(" °C")

array(['22.5', '18', '22', '20', '25', '25.6', '21', '18-25', '24.5',
       '28.5', '15', '24', '26', '15-25', '20-25', '27.5', '23', '18-27',
       '-5', '10-24', '25.5', '28', '', '30', '16', '14.5', '10-20', '19',
       '10-25', '16.5', '20.5', '8-15', '10', '12.5', '12', '18.5',
       '15-30', '15-20', '10-15', '10.5', '21.5', '17', '7', '18-24',
       '14', '15.5', '5-20', '15.6', '17.5', '15.3', '19.7', '-5.8',
       '10-30', '20-30', '25-35', '20-24', '23.5', '10-18', '8-20',
       '18-30', '18.6', '8-25', '5-25', '20.3', '4.5', '18-22', '25-30',
       '10-35', '27', '8-24', '15-27', '12-16', '7.5', '10-21', '-10',
       '25.3', '5-15', '30.5', '10.6', '19.5', '18-26'], dtype=object)

In [21]:
seedData

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18,30000,70,25,0.25
1,Flowering Plant,Montana Jack,10.0,18,15°C,8 hours,60%,50 mm,0.3 m³/m³
2,Flower,Moravsky Div,5.0,22,18,18000,60,20,0.3
3,Flowering Plant,Morden Early,5.0,22,18,300,60,20,0.3
4,Tomato,Mortgage Lifter,5.0,18,22,3000,70,50,0.3
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,20-25,15-20,6-8,40-60,20-30,0.2-0.3
4090,Herb,Valeriana Locusta,5.0,16,18,6000,60,40,0.3
4091,Herb,Valerianella Dentata,5.0,18,15,300,60,10,0.4
4092,Flowering Perennial,Verbascum roripifolium,5.0,18,15,24000,60,50,0.3
4093,Flowering Plant,Zinnia Violacea,5.0,25,20,6000,50,20,0.3

In [22]:
seedData["Average Temperature (2 m)"] = seedData["Average Temperature (2 m)"].apply(replace_str_nan)
#

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\615995419.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Temperature (2 m)"] = seedData["Average Temperature (2 m)"].apply(replace_str_nan)

In [23]:
seedData["Average Temperature (2 m)"] = seedData["Average Temperature (2 m)"].astype(str).apply(calculate_mean_value)
seedData["Average Temperature (2 m)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\638171812.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Temperature (2 m)"] = seedData["Average Temperature (2 m)"].astype(str).apply(calculate_mean_value)

array([ 22.5,  18. ,  22. ,  20. ,  25. ,  25.6,  21. ,  21.5,  24.5,
        28.5,  15. ,  24. ,  26. ,  27.5,  23. ,  -5. ,  17. ,  25.5,
        28. ,   nan,  30. ,  16. ,  14.5,  19. ,  17.5,  16.5,  20.5,
        11.5,  10. ,  12.5,  12. ,  18.5,  10.5,   7. ,  14. ,  15.5,
        15.6,  15.3,  19.7,  -5.8,  23.5,  18.6,  20.3,   4.5,  27. ,
         7.5, -10. ,  25.3,  30.5,  10.6,  19.5])

In [24]:
seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].fillna(seedData["Average Temperature (2 m)"].mean())
seedData["Average Temperature (2 m)"].isna().sum()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\675539585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Temperature (2 m)"]=seedData["Average Temperature (2 m)"].fillna(seedData["Average Temperature (2 m)"].mean())

0

In [25]:
seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].str.replace("to","-")
seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].str.replace(" ","")
seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].str.strip("°C")
seedData["Average Soil Temperature (0 to 6 cm)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3350411600.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3350411600.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3350411600.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].str.strip("°C")

array(['18', '15', '22', '20', '23.8', '14', '28', '15-20', '18.7',
       '21.3', '26.3', '16', '24', '12', '10-15', '22.3', '25.2', '25',
       '10', '18.3', '18-22', '10-20', '15-25', '22.1', '2', '12-18',
       '21.7', '', '35', '20.2', '18-25', '12.8', '15.2', '18.2', '5-10',
       '14.2', '8', '10.8', '8-20', '21.8', '12.3', '15.7', '22.7',
       '8-15', '21.2', '15.3', '16.8', '4', '11.8', '10.2', '20.3',
       '12-20', '5-15', '15.8', '8-12', '12-15', '3', '14.8', '16.5',
       '13.8', '5.1', '5', '20-30', '20-25', '19.8', '20.8', '19.2',
       '15-30', '18.9', '10-25', '10.3', '18-24', '17', '25-35', '5-18',
       '13', '17.2', '15.4', '8-18', '27', '30', '5-20', '18.5', '6.2',
       '8.2', '21', '8.7', '10.5', '25-30', '23.4', '4-10', '12.7',
       '22.8'], dtype=object)

In [26]:
seedData["Average Soil Temperature (0 to 6 cm)"] = seedData["Average Soil Temperature (0 to 6 cm)"].apply(replace_str_nan)
seedData["Average Soil Temperature (0 to 6 cm)"].isna().sum()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\509307810.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Temperature (0 to 6 cm)"] = seedData["Average Soil Temperature (0 to 6 cm)"].apply(replace_str_nan)

4

In [27]:
seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].astype(str).apply(calculate_mean_value)

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1951951577.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Temperature (0 to 6 cm)"]=seedData["Average Soil Temperature (0 to 6 cm)"].astype(str).apply(calculate_mean_value)

In [28]:
seedData["Average Soil Temperature (0 to 6 cm)"] = seedData["Average Soil Temperature (0 to 6 cm)"].fillna(seedData["Average Soil Temperature (0 to 6 cm)"].mean())

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1687259135.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Temperature (0 to 6 cm)"] = seedData["Average Soil Temperature (0 to 6 cm)"].fillna(seedData["Average Soil Temperature (0 to 6 cm)"].mean())

In [29]:
seedData["Average Sunshine Duration"].unique()

array(['30000', '8 hours', '18000', '300', '3000', '6000', '28500',
       '3600', '600', '5000', '24000', '600 seconds', '2400-2800', '8000',
       '28800', '12000', '43200', '4000-5000', '60000', '7200',
       '2000-2500', '6000-8000', '6-8', '3000 seconds', '6 - 8',
       '18000-22000', '300 seconds', '18000-20000', '18000 seconds',
       '24000-28000', '600-800', '3600 seconds', ' ', '6000-7000',
       '28000', '900', '10 seconds', '2000', '54000', '1200-1500',
       '21600', '3000-4000', '25000', '4-6', '10000', '3000-3500', '4-8',
       '2400', '6 to 8', '20000', '5000-6000', '23000', '23400',
       '2400 seconds', '24000-30000', '3600-4000', '6 hours', '26000',
       '23500', '18000 - 22000', '1200-1600', '2400-2600', '4200 seconds',
       '5-8', '5,400 seconds', '32400', '5000 seconds', '3000 - 3500',
       '2000-2200', '18000-21000', '120 seconds', '32000', '6-8 hours',
       '4 - 6', '8-10', '9000', '36000', '6300', '500 seconds',
       '6000 - 8000', 'Varies depending on the region', '26400',
       '4-8 hours', '27000', '12 hours', '4200', '3600 - 4200', nan,
       '4500', '24000-27000', '18000-23000', '24000-26000', '3200',
       '1800-2200', '4-6 seconds', '4000', '5400', '1200 to 1600',
       '1800 seconds', '2800 seconds', '800 seconds', '240-300', '25600',
       '4-6 hours', '1800', '18000 - 20000', '500-800', '31500',
       '20000-25000', '18000-25000', '8000-9000', '240 seconds', '22400',
       '86400', '24000 - 26000', '24000 - 30000', '6 - 8 hours', '40000',
       '4800', '180 seconds', '8', '24000 - 28000', '240', '25800',
       '45000', '18000-24000', '25200'], dtype=object)

hours:8,6,6,,7,12,5,7
0-12 is range for hours
minutes: 
Second values: 
600,3000,300,3600,10,2400,4200,5400,5000,120,500,5,1800,2800,800,240,180
average :1820.88

different issues in column = Average Sunshine Duration:
nan,800 seconds,6 - 8 hours,5-8,4 - 6,6 to 8,6 hours,5,400 seconds,Varies depending on the region

In [30]:
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace(" seconds","_s")
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace(" hours","_h")
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace(" ","")
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace("to","-")
seedData[["Average Sunshine Duration","unit"]]=seedData["Average Sunshine Duration"].str.split("_",n=1,expand=True)
seedData["Average Sunshine Duration"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1545571568.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace(" seconds","_s")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1545571568.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace(" hours","_h")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1545571568.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1545571568.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1545571568.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData[["Average Sunshine Duration","unit"]]=seedData["Average Sunshine Duration"].str.split("_",n=1,expand=True)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1545571568.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData[["Average Sunshine Duration","unit"]]=seedData["Average Sunshine Duration"].str.split("_",n=1,expand=True)

array(['30000', '8', '18000', '300', '3000', '6000', '28500', '3600',
       '600', '5000', '24000', '2400-2800', '8000', '28800', '12000',
       '43200', '4000-5000', '60000', '7200', '2000-2500', '6000-8000',
       '6-8', '18000-22000', '18000-20000', '24000-28000', '600-800', '',
       '6000-7000', '28000', '900', '10', '2000', '54000', '1200-1500',
       '21600', '3000-4000', '25000', '4-6', '10000', '3000-3500', '4-8',
       '2400', '20000', '5000-6000', '23000', '23400', '24000-30000',
       '3600-4000', '6', '26000', '23500', '1200-1600', '2400-2600',
       '4200', '5-8', '5,400', '32400', '2000-2200', '18000-21000', '120',
       '32000', '8-10', '9000', '36000', '6300', '500',
       'Variesdependingontheregion', '26400', '27000', '12', '3600-4200',
       nan, '4500', '24000-27000', '18000-23000', '24000-26000', '3200',
       '1800-2200', '4000', '5400', '1800', '2800', '800', '240-300',
       '25600', '500-800', '31500', '20000-25000', '18000-25000',
       '8000-9000', '240', '22400', '86400', '40000', '4800', '180',
       '25800', '45000', '18000-24000', '25200'], dtype=object)

issues found in column = Average Sunshine Duration:
nan, seconds, hours,",",24000 - 28000,to,complete string value

In [31]:
seedData

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm),unit
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000,70,25,0.25,None
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,8,60%,50 mm,0.3 m³/m³,h
2,Flower,Moravsky Div,5.0,22.0,18.0,18000,60,20,0.3,None
3,Flowering Plant,Morden Early,5.0,22.0,18.0,300,60,20,0.3,None
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000,70,50,0.3,None
...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,6-8,40-60,20-30,0.2-0.3,None
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000,60,40,0.3,None
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,300,60,10,0.4,None
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000,60,50,0.3,None
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000,50,20,0.3,None

In [32]:
seedData.loc[seedData["Average Sunshine Duration"].str.contains(r"[a-zA-Z]",na=False),"Average Sunshine Duration"]=np.nan
seedData["Average Sunshine Duration"].unique()

array(['30000', '8', '18000', '300', '3000', '6000', '28500', '3600',
       '600', '5000', '24000', '2400-2800', '8000', '28800', '12000',
       '43200', '4000-5000', '60000', '7200', '2000-2500', '6000-8000',
       '6-8', '18000-22000', '18000-20000', '24000-28000', '600-800', '',
       '6000-7000', '28000', '900', '10', '2000', '54000', '1200-1500',
       '21600', '3000-4000', '25000', '4-6', '10000', '3000-3500', '4-8',
       '2400', '20000', '5000-6000', '23000', '23400', '24000-30000',
       '3600-4000', '6', '26000', '23500', '1200-1600', '2400-2600',
       '4200', '5-8', '5,400', '32400', '2000-2200', '18000-21000', '120',
       '32000', '8-10', '9000', '36000', '6300', '500', nan, '26400',
       '27000', '12', '3600-4200', '4500', '24000-27000', '18000-23000',
       '24000-26000', '3200', '1800-2200', '4000', '5400', '1800', '2800',
       '800', '240-300', '25600', '500-800', '31500', '20000-25000',
       '18000-25000', '8000-9000', '240', '22400', '86400', '40000',
       '4800', '180', '25800', '45000', '18000-24000', '25200'],
      dtype=object)

In [33]:
seedData["Average Sunshine Duration"] = seedData["Average Sunshine Duration"].str.replace(",","")
seedData["Average Sunshine Duration"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\900242909.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"] = seedData["Average Sunshine Duration"].str.replace(",","")

array(['30000', '8', '18000', '300', '3000', '6000', '28500', '3600',
       '600', '5000', '24000', '2400-2800', '8000', '28800', '12000',
       '43200', '4000-5000', '60000', '7200', '2000-2500', '6000-8000',
       '6-8', '18000-22000', '18000-20000', '24000-28000', '600-800', '',
       '6000-7000', '28000', '900', '10', '2000', '54000', '1200-1500',
       '21600', '3000-4000', '25000', '4-6', '10000', '3000-3500', '4-8',
       '2400', '20000', '5000-6000', '23000', '23400', '24000-30000',
       '3600-4000', '6', '26000', '23500', '1200-1600', '2400-2600',
       '4200', '5-8', '5400', '32400', '2000-2200', '18000-21000', '120',
       '32000', '8-10', '9000', '36000', '6300', '500', nan, '26400',
       '27000', '12', '3600-4200', '4500', '24000-27000', '18000-23000',
       '24000-26000', '3200', '1800-2200', '4000', '1800', '2800', '800',
       '240-300', '25600', '500-800', '31500', '20000-25000',
       '18000-25000', '8000-9000', '240', '22400', '86400', '40000',
       '4800', '180', '25800', '45000', '18000-24000', '25200'],
      dtype=object)

In [34]:
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].apply(replace_str_nan)
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].astype(str).apply(calculate_mean_value)
seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].fillna(seedData["Average Sunshine Duration"].mean())
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\10229556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].apply(replace_str_nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\10229556.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].astype(str).apply(calculate_mean_value)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\10229556.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Sunshine Duration"]=seedData["Average Sunshine Duration"].fillna(seedData["Average Sunshine Duration"].mean())

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm),unit
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70,25,0.25,None
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,8.0,60%,50 mm,0.3 m³/m³,h
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60,20,0.3,None
3,Flowering Plant,Morden Early,5.0,22.0,18.0,300.0,60,20,0.3,None
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70,50,0.3,None
...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,7.0,40-60,20-30,0.2-0.3,None
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60,40,0.3,None
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,300.0,60,10,0.4,None
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60,50,0.3,None
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50,20,0.3,None

In [35]:
def calculate_duration(i):
    if seedData.loc[i,"Average Sunshine Duration"] >=0 and seedData.loc[i,"Average Sunshine Duration"] <=24:
         return (float(seedData.loc[i,"Average Sunshine Duration"])*3600)
    elif seedData.loc[i,"Average Sunshine Duration"] >24 and seedData.loc[i,"Average Sunshine Duration"] <=1800:
         return (float(seedData.loc[i,"Average Sunshine Duration"])*60)
    else:
         return (float(seedData.loc[i,"Average Sunshine Duration"]))

In [36]:
for i in seedData.index:
    if (seedData.loc[i,"unit"] == None or seedData.loc[i,"unit"]==np.nan):
        seedData.loc[i,"Average Sunshine Duration"] = calculate_duration(i)
    elif (seedData.loc[i,"unit"] == "s"):
        seedData.loc[i,"Average Sunshine Duration"]=float(seedData.loc[i,"Average Sunshine Duration"])
    else:
        seedData.loc[i,"Average Sunshine Duration"]=(float(seedData.loc[i,"Average Sunshine Duration"])*3600)

In [37]:
seedData

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm),unit
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70,25,0.25,None
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,28800.0,60%,50 mm,0.3 m³/m³,h
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60,20,0.3,None
3,Flowering Plant,Morden Early,5.0,22.0,18.0,18000.0,60,20,0.3,None
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70,50,0.3,None
...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,25200.0,40-60,20-30,0.2-0.3,None
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60,40,0.3,None
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,18000.0,60,10,0.4,None
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60,50,0.3,None
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50,20,0.3,None

unique values of unit column
[None 'h' 's' nan]

In [38]:
seedData["Humidity(%)"].unique()

array(['70', '60%', '60', '65', '40-70', '40-60', '75', '50-70', '60-70',
       '50', '70%', '40 - 60', '70 %', '50%', ' ', '20', '60 %', '60-80',
       '55', '40 to 60', '80', '70-80', '65%', '50-60%', '60 - 80', '45',
       '40 - 70', 'Varies depending on the region', '55%', '50-70%',
       '40-80', '50 - 70', '40-60%', '40-70%', '30-70', '40', '40 - 60%',
       '78'], dtype=object)

isuues in column to deal: Humidity(%):
data variety:
60%,40-70',75,40 - 60,70 %,40 to 60,50-60%,Varies depending on the region,
to solve:
1)strip " %'"
2)replace to with -
3)replace string with nan
4)replace " " with ""

In [39]:
seedData["Humidity(%)"]=seedData["Humidity(%)"].str.strip(" %'")
seedData["Humidity(%)"] = seedData["Humidity(%)"].str.replace("to","-")
seedData["Humidity(%)"] = seedData["Humidity(%)"].str.replace(" ","")
seedData["Humidity(%)"] = seedData["Humidity(%)"].apply(replace_str_nan)

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1832934971.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Humidity(%)"]=seedData["Humidity(%)"].str.strip(" %'")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1832934971.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Humidity(%)"] = seedData["Humidity(%)"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1832934971.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Humidity(%)"] = seedData["Humidity(%)"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1832934971.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Humidity(%)"] = seedData["Humidity(%)"].apply(replace_str_nan)

In [40]:
seedData.loc[seedData["Humidity(%)"].str.contains(r"[a-zA-Z]", na=False), "Humidity(%)"] = np.nan

seedData["Humidity(%)"].unique()

array(['70', '60', '65', '40-70', '40-60', '75', '50-70', '60-70', '50',
       nan, '20', '60-80', '55', '80', '70-80', '50-60', '45', '40-80',
       '30-70', '40', '78'], dtype=object)

In [41]:
seedData["Humidity(%)"] = seedData["Humidity(%)"].astype(str).apply(calculate_mean_value)
seedData["Humidity(%)"] = seedData["Humidity(%)"].fillna(seedData["Humidity(%)"].mean())
seedData["Humidity(%)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1056752676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Humidity(%)"] = seedData["Humidity(%)"].astype(str).apply(calculate_mean_value)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1056752676.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Humidity(%)"] = seedData["Humidity(%)"].fillna(seedData["Humidity(%)"].mean())

array([70.        , 60.        , 65.        , 55.        , 50.        ,
       75.        , 61.68866536, 20.        , 80.        , 45.        ,
       40.        , 78.        ])

In [42]:
seedData

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm),unit
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70.0,25,0.25,None
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,28800.0,60.0,50 mm,0.3 m³/m³,h
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60.0,20,0.3,None
3,Flowering Plant,Morden Early,5.0,22.0,18.0,18000.0,60.0,20,0.3,None
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70.0,50,0.3,None
...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,25200.0,50.0,20-30,0.2-0.3,None
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60.0,40,0.3,None
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,18000.0,60.0,10,0.4,None
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60.0,50,0.3,None
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50.0,20,0.3,None

In [43]:
seedData["Rainfall Alert Maximum Rain (mm)"].unique()

array(['25', '50 mm', '20', '50', '30', '100', '10', '15', '20 mm',
       '50-100', '20-30', '10 mm', '20mm', '40', '100 mm', '30 mm', ' ',
       '0', '50-60', '10-20', '15-20', '50-70', '15 mm', '30-50', '50mm',
       '50-100 mm', '10mm', '20 - 30', 'Varies depending on the region',
       nan, '10-15', '10-20 mm', '30-40', '20-40', '40-60', '100-150',
       '50-75', '10 - 20', '2000', '50 - 100'], dtype=object)

1)strip " m"
2)replace empty string with nan
3)replace " " with ""
4)replace string characters with nan
5)calculate mean
6)fill nan values with mean

In [44]:
seedData["Rainfall Alert Maximum Rain (mm)"]=seedData["Rainfall Alert Maximum Rain (mm)"].str.strip(" m")
seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].str.replace(" ","")
seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].apply(replace_str_nan)
seedData.loc[seedData["Rainfall Alert Maximum Rain (mm)"].str.contains(r"[a-zA-Z]", na=False), "Rainfall Alert Maximum Rain (mm)"] = np.nan
seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].astype(str).apply(calculate_mean_value)
seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].fillna(seedData["Rainfall Alert Maximum Rain (mm)"].mean())
seedData["Rainfall Alert Maximum Rain (mm)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3599722379.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Rainfall Alert Maximum Rain (mm)"]=seedData["Rainfall Alert Maximum Rain (mm)"].str.strip(" m")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3599722379.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3599722379.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].apply(replace_str_nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3599722379.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].astype(str).apply(calculate_mean_value)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3599722379.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Rainfall Alert Maximum Rain (mm)"] = seedData["Rainfall Alert Maximum Rain (mm)"].fillna(seedData["Rainfall Alert Maximum Rain (mm)"].mean())

array([  25.        ,   50.        ,   20.        ,   30.        ,
        100.        ,   10.        ,   15.        ,   75.        ,
         40.        ,   26.99877301,    0.        ,   55.        ,
         17.5       ,   60.        ,   12.5       ,   35.        ,
        125.        ,   62.5       , 2000.        ])

In [45]:
seedData

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration,Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm),unit
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70.0,25.0,0.25,None
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,28800.0,60.0,50.0,0.3 m³/m³,h
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60.0,20.0,0.3,None
3,Flowering Plant,Morden Early,5.0,22.0,18.0,18000.0,60.0,20.0,0.3,None
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70.0,50.0,0.3,None
...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,25200.0,50.0,25.0,0.2-0.3,None
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60.0,40.0,0.3,None
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,18000.0,60.0,10.0,0.4,None
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60.0,50.0,0.3,None
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50.0,20.0,0.3,None

In [46]:
seedData.rename(columns={"Average Sunshine Duration":"Average Sunshine Duration(s)"},inplace=True)
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\635554507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData.rename(columns={"Average Sunshine Duration":"Average Sunshine Duration(s)"},inplace=True)

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration(s),Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm),unit
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70.0,25.0,0.25,None
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,28800.0,60.0,50.0,0.3 m³/m³,h
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60.0,20.0,0.3,None
3,Flowering Plant,Morden Early,5.0,22.0,18.0,18000.0,60.0,20.0,0.3,None
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70.0,50.0,0.3,None
...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,25200.0,50.0,25.0,0.2-0.3,None
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60.0,40.0,0.3,None
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,18000.0,60.0,10.0,0.4,None
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60.0,50.0,0.3,None
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50.0,20.0,0.3,None

In [47]:
seedData.drop(columns=["unit"],inplace=True)
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1412916708.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData.drop(columns=["unit"],inplace=True)

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration(s),Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70.0,25.0,0.25
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,28800.0,60.0,50.0,0.3 m³/m³
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60.0,20.0,0.3
3,Flowering Plant,Morden Early,5.0,22.0,18.0,18000.0,60.0,20.0,0.3
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70.0,50.0,0.3
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,25200.0,50.0,25.0,0.2-0.3
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60.0,40.0,0.3
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,18000.0,60.0,10.0,0.4
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60.0,50.0,0.3
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50.0,20.0,0.3

In [48]:
seedData["Average Soil Moisture (0-3 cm)"].unique()

array(['0.25', '0.3 m³/m³', '0.3', '0.4', '0.32', '0.2', '0.5', '0.2-0.4',
       '0.35', '0.3-0.5', '0.2 m³/m³', '0.2-0.3', '0.28', '0.25-0.35',
       '0.3 - 0.5', '0.25 m³/m³', ' ', '0.3-0.4', '0.27', '0.4-0.6',
       '0.3 to 0.5', '0.3-0.6', '0.2-0.6', '0.45', '0.23', '0.4 m³/m³',
       '0.5 m³/m³', '0.24', '0.2 - 0.4', '0.22 m³/m³', '0.2-0.5',
       '0.2 - 0.3', '0.6', '0.3m³/m³', '20-30 m³/m³', '0.18', '0.25-0.4',
       '0.15-0.25', '0.2-0.4 m³/m³', '0.1-0.3', '40-60', '0.15 - 0.25',
       '0.16', '0.35 m³/m³', '30-40', '30-50', '20-30', '0.15-0.25 m³/m³',
       '0.3-0.5 m³/m³', '30-60', '20-40', '0.35-0.45', '0.25-0.35 m³/m³',
       '0.15', '0.3-0.6 m³/m³', '0.25 - 0.35', '0.5-0.8', '0.22', '0.8',
       '0.3 - 0.6', '0.2 - 0.4 m³/m³', '0.42'], dtype=object)

issues in above column :
0.3 m³/m³,0.2-0.4,0.3 - 0.5,' ',0.3 to 0.5,
to do:
1)strip " m³/m³"
2)replace space with empty string
3)replace empty string with nan
4)replace tp with "-"
5)calculate mean

In [49]:
seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].str.strip(" m³/m³")
seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].str.replace(" ","")
seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].str.replace("to","-")
seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].astype(str).apply(replace_str_nan)
seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].astype(str).apply(calculate_mean_value)
seedData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3750549931.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].str.strip(" m³/m³")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3750549931.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3750549931.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3750549931.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].astype(str).apply(replace_str_nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3750549931.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].astype(str).apply(calculate_mean_value)

,Plant Category,Seed Name,Average Precipitation per day,Average Temperature (2 m),Average Soil Temperature (0 to 6 cm),Average Sunshine Duration(s),Humidity(%),Rainfall Alert Maximum Rain (mm),Average Soil Moisture (0-3 cm)
0,Herbaceous perennial,Monarde citron,3.5,22.5,18.0,30000.0,70.0,25.0,0.25
1,Flowering Plant,Montana Jack,10.0,18.0,15.0,28800.0,60.0,50.0,0.30
2,Flower,Moravsky Div,5.0,22.0,18.0,18000.0,60.0,20.0,0.30
3,Flowering Plant,Morden Early,5.0,22.0,18.0,18000.0,60.0,20.0,0.30
4,Tomato,Mortgage Lifter,5.0,18.0,22.0,3000.0,70.0,50.0,0.30
...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,7.5,22.5,17.5,25200.0,50.0,25.0,0.25
4090,Herb,Valeriana Locusta,5.0,16.0,18.0,6000.0,60.0,40.0,0.30
4091,Herb,Valerianella Dentata,5.0,18.0,15.0,18000.0,60.0,10.0,0.40
4092,Flowering Perennial,Verbascum roripifolium,5.0,18.0,15.0,24000.0,60.0,50.0,0.30
4093,Flowering Plant,Zinnia Violacea,5.0,25.0,20.0,6000.0,50.0,20.0,0.30

In [50]:
seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].fillna(seedData["Average Soil Moisture (0-3 cm)"].mean())
seedData["Average Soil Moisture (0-3 cm)"].isna().sum()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1743935913.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seedData["Average Soil Moisture (0-3 cm)"] = seedData["Average Soil Moisture (0-3 cm)"].fillna(seedData["Average Soil Moisture (0-3 cm)"].mean())

0

In [51]:
seedData.to_csv("seedDataSheet.csv",index=False)

In [52]:
merged_df_copy

,Plant Category,Seed Name,Average Temperature (2 m),Average Precipitation per day,Average Soil Temperature (0 to 6 cm),Average Soil Moisture (0-3 cm),Average Evapotranspiration,Average Sunshine Duration,Humidity(%),Soil Type,...,Wind Threshold(km/h),Heat Wave Maximum Temprature (°C),Rainfall Alert Maximum Rain (mm),Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Maximum Height of Plant (inches),Maximum area this plant require (inches),Soil depth for sowing (inches),Plant name
0,Herbaceous perennial,Monarde citron,22.5,3.5,18,0.25,3,30000,70,"[""Loam"",""Sandy loam"",""Clay loam""]",...,40,35,25,48,"[""Organic compost"",""Liquid seaweed fertilizer""]",4,36,12,1,monarde citron
1,Flowering Plant,Montana Jack,18°C,10 mm,15°C,0.3 m³/m³,5 mm/day,8 hours,60%,"[""Loam"",""Sandy Loam"",""Clay Loam""]",...,50 km/h,35°C,50 mm,48 hours,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8 weeks,24 inches,12 inches,1 inch,montana jack
2,Flower,Moravsky Div,22,5,18,0.3,4,18000,60,"[""Loam"",""Sandy Loam""]",...,40,35,20,24,"[""NPK 10-10-10"",""Compost""]",4,24,12,0.5,moravsky div
3,Flowering Plant,Morden Early,22,5,18,0.3,3,300,60,"[""Loam"",""Clay"",""Sandy""]",...,40,35,20,24,"[""Organic compost"",""Slow-release granular fert...",4,24,12,0.5,morden early
4,Tomato,Mortgage Lifter,18,5,22,0.3,3,3000,70,"[""Loam"",""Sandy Loam"",""Clay Loam""]",...,40,35,50,24,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2,72,36,1,mortgage lifter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,20-25,5-10,15-20,0.2-0.3,3-5,6-8,40-60,"[""Sandy loam"",""Loamy sand"",""Clay loam""]",...,40-60,30-35,20-30,24-48,"[""Organic compost"",""Slow-release granular fert...",4-6,12-18,12-18,0.25-0.5,ursinia anthemoides
4090,Herb,Valeriana Locusta,16,5,18,0.3,3,6000,60,"[""Loam"",""Sandy loam""]",...,40,35,40,72,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,24,12,0.5,valeriana locusta
4091,Herb,Valerianella Dentata,18,5,15,0.4,3,300,60,"[""Loamy"",""Sandy""]",...,40,30,10,48,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,12,6,0.5,valerianella dentata
4092,Flowering Perennial,Verbascum roripifolium,18,5,15,0.3,3,24000,60,"[""Loam"",""Sandy Loam"",""Clay""]",...,40,35,50,48,"[""Organic compost"",""All-purpose slow-release f...",6,36,144,0.25,verbascum roripifolium
4093,Flowering Plant,Zinnia Violacea,25,5,20,0.3,3,6000,50,"[""Loam"",""Sandy Loam"",""Clay""]",...,40,35,20,24,"[""NPK 10-10-10"",""Organic compost""]",4,36,12,0.5,zinnia violacea

In [53]:
cultData=merged_df_copy[["Plant Category","Seed Name","Watering (hours interval)","List of Fertilization","Time Period for Fertilization (weeks interval)","Soil depth for sowing (inches)","Plant name"]]
cultData

,Plant Category,Seed Name,Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Soil depth for sowing (inches),Plant name
0,Herbaceous perennial,Monarde citron,48,"[""Organic compost"",""Liquid seaweed fertilizer""]",4,1,monarde citron
1,Flowering Plant,Montana Jack,48 hours,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8 weeks,1 inch,montana jack
2,Flower,Moravsky Div,24,"[""NPK 10-10-10"",""Compost""]",4,0.5,moravsky div
3,Flowering Plant,Morden Early,24,"[""Organic compost"",""Slow-release granular fert...",4,0.5,morden early
4,Tomato,Mortgage Lifter,24,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2,1,mortgage lifter
...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,24-48,"[""Organic compost"",""Slow-release granular fert...",4-6,0.25-0.5,ursinia anthemoides
4090,Herb,Valeriana Locusta,72,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valeriana locusta
4091,Herb,Valerianella Dentata,48,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valerianella dentata
4092,Flowering Perennial,Verbascum roripifolium,48,"[""Organic compost"",""All-purpose slow-release f...",6,0.25,verbascum roripifolium
4093,Flowering Plant,Zinnia Violacea,24,"[""NPK 10-10-10"",""Organic compost""]",4,0.5,zinnia violacea

In [54]:
import numpy as np
cultData["Seed Name"]=cultData["Seed Name"].replace(" ",np.nan)
cultData.dropna(subset=["Seed Name"],inplace=True)
for i in seedData.index:
    if cultData.loc[i,"Seed Name"]=="Unknown":
        cultData.drop(i,inplace=True)
cultData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\4285268906.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Seed Name"]=cultData["Seed Name"].replace(" ",np.nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\4285268906.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData.dropna(subset=["Seed Name"],inplace=True)

,Plant Category,Seed Name,Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Soil depth for sowing (inches),Plant name
0,Herbaceous perennial,Monarde citron,48,"[""Organic compost"",""Liquid seaweed fertilizer""]",4,1,monarde citron
1,Flowering Plant,Montana Jack,48 hours,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8 weeks,1 inch,montana jack
2,Flower,Moravsky Div,24,"[""NPK 10-10-10"",""Compost""]",4,0.5,moravsky div
3,Flowering Plant,Morden Early,24,"[""Organic compost"",""Slow-release granular fert...",4,0.5,morden early
4,Tomato,Mortgage Lifter,24,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2,1,mortgage lifter
...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,24-48,"[""Organic compost"",""Slow-release granular fert...",4-6,0.25-0.5,ursinia anthemoides
4090,Herb,Valeriana Locusta,72,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valeriana locusta
4091,Herb,Valerianella Dentata,48,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valerianella dentata
4092,Flowering Perennial,Verbascum roripifolium,48,"[""Organic compost"",""All-purpose slow-release f...",6,0.25,verbascum roripifolium
4093,Flowering Plant,Zinnia Violacea,24,"[""NPK 10-10-10"",""Organic compost""]",4,0.5,zinnia violacea

In [55]:
cultData["Watering (hours interval)"].unique()

array(['48', '48 hours', '24', '6 hours', '24-48', '72', '48-72', '36',
       '24 hours', '12 hours', 'Every 2 days', 'Every 2-3 days',
       '24 - 48', ' ', 'Once every 2 weeks', '6', '72-96', '12',
       '72 hours', '7-10', '48 - 72', '2-3 hours', '4', '1-2', '2-3',
       '12-24 hours', '48-72 hours', '12-24', 'Every 3 days',
       'Every 3-4 days', 'Unknown', 'Every 2 - 3 days', '2 hours', '2'],
      dtype=object)

issues in column Watering (hours interval):
48 hours,24-48,Every 2 days,Every 2-3 days,24 - 48,' ',Once every 2 weeks,2-3 hours,Every 3 days,Every 3-4 days,Unknown,very 2 - 3 days
To do:
1)replace " hours" with "_h"," days" with "_d"," weeks" with "_w"
2)strip "Every Once every Unknown very"
3)replace " " with empty string
4)repllace empty string with with nan
5)calculate mean

In [56]:
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" hours","_h")
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" days","_d")
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" weeks","_w")
cultData["Watering (hours interval)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\2186217550.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" hours","_h")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\2186217550.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" days","_d")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\2186217550.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" weeks","_w")

array(['48', '48_h', '24', '6_h', '24-48', '72', '48-72', '36', '24_h',
       '12_h', 'Every 2_d', 'Every 2-3_d', '24 - 48', ' ',
       'Once every 2_w', '6', '72-96', '12', '72_h', '7-10', '48 - 72',
       '2-3_h', '4', '1-2', '2-3', '12-24_h', '48-72_h', '12-24',
       'Every 3_d', 'Every 3-4_d', 'Unknown', 'Every 2 - 3_d', '2_h', '2'],
      dtype=object)

In [57]:
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.strip("Every Once every very")
cultData["Watering (hours interval)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\1432857132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.strip("Every Once every very")

array(['48', '48_h', '24', '6_h', '24-48', '72', '48-72', '36', '24_h',
       '12_h', '2_d', '2-3_d', '24 - 48', '', '2_w', '6', '72-96', '12',
       '72_h', '7-10', '48 - 72', '2-3_h', '4', '1-2', '2-3', '12-24_h',
       '48-72_h', '12-24', '3_d', '3-4_d', 'Unknow', '2 - 3_d', '2_h',
       '2'], dtype=object)

In [59]:
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace("Unknow","")
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" ","")
cultData["Watering (hours interval)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\448809177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace("Unknow","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\448809177.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].str.replace(" ","")

array(['48', '48_h', '24', '6_h', '24-48', '72', '48-72', '36', '24_h',
       '12_h', '2_d', '2-3_d', '', '2_w', '6', '72-96', '12', '72_h',
       '7-10', '2-3_h', '4', '1-2', '2-3', '12-24_h', '48-72_h', '12-24',
       '3_d', '3-4_d', '2_h', '2'], dtype=object)

In [60]:
cultData[["Watering (hours interval)","water unit"]] = cultData["Watering (hours interval)"].str.split("_",n=1,expand=True)
cultData

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\644765302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData[["Watering (hours interval)","water unit"]] = cultData["Watering (hours interval)"].str.split("_",n=1,expand=True)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\644765302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData[["Watering (hours interval)","water unit"]] = cultData["Watering (hours interval)"].str.split("_",n=1,expand=True)

,Plant Category,Seed Name,Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Soil depth for sowing (inches),Plant name,water unit
0,Herbaceous perennial,Monarde citron,48,"[""Organic compost"",""Liquid seaweed fertilizer""]",4,1,monarde citron,None
1,Flowering Plant,Montana Jack,48,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8 weeks,1 inch,montana jack,h
2,Flower,Moravsky Div,24,"[""NPK 10-10-10"",""Compost""]",4,0.5,moravsky div,None
3,Flowering Plant,Morden Early,24,"[""Organic compost"",""Slow-release granular fert...",4,0.5,morden early,None
4,Tomato,Mortgage Lifter,24,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2,1,mortgage lifter,None
...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,24-48,"[""Organic compost"",""Slow-release granular fert...",4-6,0.25-0.5,ursinia anthemoides,None
4090,Herb,Valeriana Locusta,72,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valeriana locusta,None
4091,Herb,Valerianella Dentata,48,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valerianella dentata,None
4092,Flowering Perennial,Verbascum roripifolium,48,"[""Organic compost"",""All-purpose slow-release f...",6,0.25,verbascum roripifolium,None
4093,Flowering Plant,Zinnia Violacea,24,"[""NPK 10-10-10"",""Organic compost""]",4,0.5,zinnia violacea,None

In [61]:
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].astype(str).apply(replace_str_nan)
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].astype(str).apply(calculate_mean_value)
cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].fillna(cultData["Watering (hours interval)"].mean())
cultData["Watering (hours interval)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\582727141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].astype(str).apply(replace_str_nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\582727141.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].astype(str).apply(calculate_mean_value)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\582727141.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Watering (hours interval)"] = cultData["Watering (hours interval)"].fillna(cultData["Watering (hours interval)"].mean())

array([48.        , 24.        ,  6.        , 36.        , 72.        ,
       60.        , 12.        ,  2.        ,  2.5       , 44.29556046,
       84.        ,  8.5       ,  4.        ,  1.5       , 18.        ,
        3.        ,  3.5       ])

In [64]:
cultData["water unit"].unique()

array([None, 'h', 'd', 'w'], dtype=object)

In [69]:
for i in cultData.index:
    if (cultData.loc[i,"water unit"] == None or cultData.loc[i,"water unit"]==np.nan):
        cultData.loc[i,"Watering (hours interval)"]=float(cultData.loc[i,"Watering (hours interval)"])
    elif (cultData.loc[i,"water unit"] == "h"):
        cultData.loc[i,"Watering (hours interval)"]=float(cultData.loc[i,"Watering (hours interval)"])
    elif (cultData.loc[i,"water unit"] == "d"):
        cultData.loc[i,"Watering (hours interval)"]=(float(cultData.loc[i,"Watering (hours interval)"])*24)    
    else:
        cultData.loc[i,"Watering (hours interval)"]=(float(cultData.loc[i,"Watering (hours interval)"])*24*7)

In [70]:
cultData

,Plant Category,Seed Name,Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Soil depth for sowing (inches),Plant name,water unit
0,Herbaceous perennial,Monarde citron,48.0,"[""Organic compost"",""Liquid seaweed fertilizer""]",4,1,monarde citron,None
1,Flowering Plant,Montana Jack,48.0,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8 weeks,1 inch,montana jack,h
2,Flower,Moravsky Div,24.0,"[""NPK 10-10-10"",""Compost""]",4,0.5,moravsky div,None
3,Flowering Plant,Morden Early,24.0,"[""Organic compost"",""Slow-release granular fert...",4,0.5,morden early,None
4,Tomato,Mortgage Lifter,24.0,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2,1,mortgage lifter,None
...,...,...,...,...,...,...,...,...
4089,Flowering plant,Ursinia anthemoides,36.0,"[""Organic compost"",""Slow-release granular fert...",4-6,0.25-0.5,ursinia anthemoides,None
4090,Herb,Valeriana Locusta,72.0,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valeriana locusta,None
4091,Herb,Valerianella Dentata,48.0,"[""Nitrogen"",""Phosphorus"",""Potassium""]",4,0.5,valerianella dentata,None
4092,Flowering Perennial,Verbascum roripifolium,48.0,"[""Organic compost"",""All-purpose slow-release f...",6,0.25,verbascum roripifolium,None
4093,Flowering Plant,Zinnia Violacea,24.0,"[""NPK 10-10-10"",""Organic compost""]",4,0.5,zinnia violacea,None

In [71]:
cultData["Time Period for Fertilization (weeks interval)"].unique()

array(['4', '8 weeks', '2', '8', '4 weeks', '2-4', '3', '4-6', '6',
       'Every 4 weeks', '4 - 6', '2-3', ' ', '6-8', '4 to 6', '10',
       'Every 4-6 weeks', '12', '6 weeks', '4-6 weeks', 'Every 2-3 weeks',
       '2 - 3', '3-4', 'Every 2 weeks', '2 weeks', '3 weeks', '3 - 4',
       'Every 3 weeks', 'Unknown', '4-8', '6 - 8', 'Every 4 - 6 weeks',
       '12-16', '4 - 8', '26'], dtype=object)

In [72]:

cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].str.strip(" weeks Every Unknown")

cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].str.replace(" ","")
cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].str.replace("to","-")

cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].astype(str).apply(replace_str_nan)
cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].astype(str).apply(calculate_mean_value)
cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].fillna(cultData["Watering (hours interval)"].mean())
cultData["Time Period for Fertilization (weeks interval)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3772392588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].str.strip(" weeks Every Unknown")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3772392588.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3772392588.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3772392588.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].astype(str).apply(replace_str_nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3772392588.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].astype(str).apply(calculate_mean_value)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3772392588.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Time Period for Fertilization (weeks interval)"] = cultData["Time Period for Fertilization (weeks interval)"].fillna(cultData["Watering (hours interval)"].mean())

array([ 4.        ,  8.        ,  2.        ,  3.        ,  5.        ,
        6.        ,  2.5       , 44.76334586,  7.        , 10.        ,
       12.        ,  3.5       , 14.        , 26.        ])

In [73]:
cultData.head()

,Plant Category,Seed Name,Watering (hours interval),List of Fertilization,Time Period for Fertilization (weeks interval),Soil depth for sowing (inches),Plant name,water unit
0,Herbaceous perennial,Monarde citron,48.0,"[""Organic compost"",""Liquid seaweed fertilizer""]",4.0,1,monarde citron,None
1,Flowering Plant,Montana Jack,48.0,"[""Nitrogen-based fertilizer"",""Phosphorus-based...",8.0,1 inch,montana jack,h
2,Flower,Moravsky Div,24.0,"[""NPK 10-10-10"",""Compost""]",4.0,0.5,moravsky div,None
3,Flowering Plant,Morden Early,24.0,"[""Organic compost"",""Slow-release granular fert...",4.0,0.5,morden early,None
4,Tomato,Mortgage Lifter,24.0,"[""Nitrogen"",""Phosphorus"",""Potassium""]",2.0,1,mortgage lifter,None

In [74]:
cultData["Soil depth for sowing (inches)"].unique()

array(['1', '1 inch', '0.5', '2', '1 in', '0.5-1', '6', '1-2', '2 in',
       '0.5 inches', '0.25-0.5', '2 inches', '0.5 in', '4', ' ', '0.2',
       '0.25', '2-4', '0.5-1.0', '1.5', '12', '0.4', '0.2 - 0.4',
       '0.25 - 0.5', '4-6', '0.5in', '2-4 in', '0.1', '4 - 6', '2-3',
       '1-2 inches', '0.6', '0.1-0.2', '2 - 3', '0.5 - 1', nan, '0.2-0.4',
       '0.5-1 inch', '0.4-0.8', 'Unknown in', '3', '0.25-0.5 inches',
       '3 - 4', '0.5 to 1'], dtype=object)

In [75]:
cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].str.strip(" inches Unknown")
cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].str.replace(" ","")
cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].str.replace("to","-")

cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].astype(str).apply(replace_str_nan)
cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].astype(str).apply(calculate_mean_value)
cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].fillna(cultData["Watering (hours interval)"].mean())
cultData["Soil depth for sowing (inches)"].unique()

C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3829089183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].str.strip(" inches Unknown")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3829089183.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].str.replace(" ","")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3829089183.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].str.replace("to","-")
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3829089183.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].astype(str).apply(replace_str_nan)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3829089183.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].astype(str).apply(calculate_mean_value)
C:\Users\PMLS\AppData\Local\Temp\ipykernel_57008\3829089183.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cultData["Soil depth for sowing (inches)"] = cultData["Soil depth for sowing (inches)"].fillna(cultData["Watering (hours interval)"].mean())

array([ 1.        ,  0.5       ,  2.        ,  0.75      ,  6.        ,
        1.5       ,  0.375     ,  4.        , 44.76334586,  0.2       ,
        0.25      ,  3.        , 12.        ,  0.4       ,  0.3       ,
        5.        ,  0.1       ,  2.5       ,  0.6       ,  0.15      ,
        0.6       ,  3.5       ])

In [76]:
cultData.to_csv("processed_cultivation.csv",index=False)